# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
#

image: node:jessie
#
# before_script:
#   - npm --version

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache

before_script:
  - export NODE_TLS_REJECT_UNAUTHORIZED=0
  - npm config set registry http://registry.npmjs.org/
  - npm config set strict-ssl false --global
  - npm config set ca ""

cache:
  paths:
    - node_modules/

stages:
  - test
  # - deploy

runTestCases:
  tags:
    - sps
  stage: test
  script:
    - npm install mocha --global
    - npm install
    - cd src
    - ls -l
    - npm test

# Currently does not work because electron cert signed by unknown authority
# buildDists:
#   tags:
#     - fruitfly
#   stage: deploy
#   script:
#     - cd gcs/src/gui
#     - yarn install
#     - yarn config set strict-ssl false --global
#     - yarn dist
